site_name: Dokumentasi Base Go DPTSI
site_url: https://example.com/
theme:
  name: material

nav:
  - Beranda: index.md
  - Memulai:
      - Struktur Direktori: struktur-direktori.md
  - Dasar:
      - Modul: basics/modul.md
      - Routing: basics/routing.md
      - Proteksi CSRF: basics/csrf.md
      - Controllers: basics/controllers.md
      - HTTP Session: basics/session.md
      - Authentication: basics/authentication.md
  - Dokumentasi OpenAPI 3.1: openapi-docs.md
  - Dokumentasi Project: project-docs.md
